### ISSUE TITLE
Add binary links to latest version

### ISSUE THREAD

**Issue by jakedeichert** [gogits/docs#106]
I might be missing this somewhere, but it appears that all binary download links are hardcoded to specific versions.

Example: https://dl.gogs.io/gogs_v0.9.13_linux_amd64.tar.gz

Would you consider also having "latest" version urls that just point to the latest binary version?

Example: https://dl.gogs.io/gogs_latest_linux_amd64.tar.gz

I'm writing a blog post about getting gogs setup with https and this would help me reference some urls. It could also help in automated environments (such as vagrant) in a scenario where you're always trying to target the latest version of gogs.

**Comment by Unknwon** [comment]
Currently, no because the download host site is completely static.

**Comment by jakedeichert** [comment]
Thanks for getting back to me @Unknwon. I'll close this for now then.

**Comment by Unknwon** [comment]
If there is any technic that could redirect with static file, I think this could happen.

**Comment by jakedeichert** [comment]
It seems that https://dl.gogs.io is served using [Caddy](https://caddyserver.com/). 

If this is the case, it might be possible to do a [url rewrite with Caddy as their docs suggest](https://caddyserver.com/docs/rewrite).

 For example, you should be able to catch this `https://dl.gogs.io/gogs_latest_linux_amd64.tar.gz` but return this `https://dl.gogs.io/gogs_v0.9.13_linux_amd64.tar.gz` or whatever the latest version is.

Just an idea. Not sure if it will work for this situation. Also, every release someone would have to update the url rewrite on the caddy server... so I'm not sure if this is a good idea.

**Comment by Unknwon** [comment]
Feels like it needs quite a few rewrites and need to update for every release...
