### ISSUE TITLE
gogs_v0.9.0_linux_amd64 升级 gogs_v0.9.13_linux_amd64 失败.

### ISSUE THREAD

**Issue by yzdel200** [gogits/docs#107]
发错地方了，请无视吧....
升级覆盖相关文件后，在服务器启动，提示警告，然后就不能访问了.
错误日志:
2016/04/07 10:09:04 [I] Gogs: Go Git Service 0.9.13.0318
2016/04/07 10:09:04 [I] Log Mode: File(Trace)
2016/04/07 10:09:04 [I] Cache Service Enabled
2016/04/07 10:09:04 [I] Session Service Enabled
2016/04/07 10:09:04 [I] Git Version: 2.1.4
2016/04/07 10:09:04 [I] Migration: convert date to unix timestamp
2016/04/07 10:09:04 [I] Converting table: action
2016/04/07 10:09:04 [T] Table [action]: offset: 0, beans: 100
2016/04/07 10:09:09 [T] Table [action]: offset: 100, beans: 100
2016/04/07 10:09:15 [T] Table [action]: offset: 200, beans: 100
2016/04/07 10:09:20 [T] Table [action]: offset: 300, beans: 100
2016/04/07 10:09:24 [T] Table [action]: offset: 400, beans: 100

**Comment by Unknwon** [comment]
hmmm?? what's going on?
