### ISSUE TITLE
Gogs 0.10.X URLs have changed

### ISSUE THREAD

**Issue by iggyvolz** [gogits/docs#151]
The "Download and unzip new binary" section of upgrade/upgrade_from_binary.md should be changed to match the new URL structure.

For 0.10.X releases, the first two lines of the script should be:
```bash
$ wget https://dl.gogs.io/$VERSION/$OS_$ARCH.tar.gz
$ tar -zxvf $OS_$ARCH.tar.gz
```

Not sure what the best way to signify that is while still making the script relevant for 0.9 releases.

**Comment by Unknwon** [comment]
Thanks! Fix pushed, should be good now!
