### ISSUE TITLE
Lighttpd change port to url

### ISSUE THREAD

**Issue by stamatovg** [gogits/docs#161]
Hello, lighttpd tutorial is outdated /this module is only available in the (now dead) 1.5.x branch./. Any idea how can i change port to url (subdomain) with lighttpd?

> How do I set up a sub-URL with lighttpd?
> 
> Use following configuration template:
> 
> ```
> server.modules  += ( "mod_proxy_backend_http" )
> $HTTP["url"] =~ "^/gogs" {
>     proxy-core.protocol = "http"
>     proxy-core.backends = ( "localhost:3000" )
>     proxy-core.rewrite-request = (
>       "_uri" => ( "^/gogs/?(.*)" => "/$1" ),
>       "Host" => ( ".*" => "localhost:3000" ),
>     )
> }
> ```

**Comment by Unknwon** [comment]
Hi... as I never used Lighttpd... maybe you can send a pull request after you figured out how?

**Comment by daftaupe** [comment]
@stamatovg what do you mean by the now dead 1.5.x branch ? On http://www.lighttpd.net/download/ I can only see 1.4.45 available.

Regards,
