### ISSUE TITLE
Escaped Quotes required for Run As Windows Service

### ISSUE THREAD

**Issue by xFleury** [gogits/docs#171]
On the [Run As Windows Service doc](https://gogs.io/docs/installation/run_as_windows_service), the instructions state:

> Open a command prompt (`cmd.exe`) as an Administrator. Run the following command:
>```
>C:\> sc create gogs start= auto binPath= ""C:\gogs\gogs.exe" web --config "C:\gogs\custom\conf\app.ini""
>```

This failed on my Windows 10 Pro computer; the command prompt simply reiterated what the syntax for the "sc" command is.

After some trial&error, I managed to get it to create the service using the following:

```
C:\> sc create gogs start= auto binPath= "\"C:\gogs\gogs.exe\" web --config \"C:\gogs\custom\conf\app.ini\""
```

**Comment by xFleury** [comment]
I found a, closed, existing issue for this. Was it closed because its author didn't respond timely?

#91 

To answer his unanswered question, yes gogs works after the quotes are escaped. I'm successfully runnings gogs as a service now.

**Comment by Unknwon** [comment]
Strange, I'm using Windows 10 too with default CMD and input exact same string from docs and it works...
