### ISSUE TITLE
LOG_RORATE - Documentation has incorrect key for LOG_ROTATE

### ISSUE THREAD

**Issue by binaryWard** [gogits/docs#185]
The config cheat sheet has "LOG_ROTATE" incorrectly spelled as "LOG_RORATE"
Found in these versions.
https://github.com/gogits/docs/blob/master/en-US/advanced/configuration_cheat_sheet.md
https://github.com/gogits/docs/blob/master/zh-CN/advanced/configuration_cheat_sheet.md

Repo search for LOG_RORATE
https://github.com/gogits/docs/search?utf8=%E2%9C%93&q=LOG_RORATE&type=

The master app.ini file has the key as LOG_ROTATE
https://github.com/gogits/gogs/blob/master/conf/app.ini

**Comment by miguel456** [comment]
This issue should be fixed by PR https://github.com/gogits/docs/pull/187.
Hope it gets merged! xD

**Comment by Unknwon** [comment]
Fixed!
