### ISSUE TITLE
REST APi

### ISSUE THREAD

**Issue by cmoulliard** [gogits/docs#43]
Is the REST APi documented somewhere with the operation that we can do as this one by example ?

````
curl -vk -u myuser:mypwd http://192.168.59.103:3000/api/v1/user/repos
````

**Comment by Unknwon** [comment]
Hmm... hasn't officially released APIs yet, there will be docs when we release!

**Comment by Unknwon** [comment]
Please see https://github.com/gogits/go-gogs-client/wiki :grinning:
