### ISSUE TITLE
Need doc on changing gogs home page look and feel

### ISSUE THREAD

**Issue by tjyang** [gogits/docs#63]
Hi 
Is it possible write up some simple steps to guy people changing the look and feel.
Ex. replace the gogs logo with a custom one.

Thanks

**Comment by Unknwon** [comment]
Currently, this has to be done by hacking the code directly, so hmm... no doc will be available.

Please follow on https://github.com/gogits/gogs/issues/1126 for official kind of support

**Comment by tjyang** [comment]
Hi Unknown
Thanks for the quick response and pointer to customized CSS files. 
Let me narrow down my goal/requst.
How about just replace the left corner Gogs icon and home page content wording ?

tj

**Comment by Unknwon** [comment]
Replace https://github.com/gogits/gogs/blob/master/public/img/gogs-lg.png with your Logo.

**Comment by tjyang** [comment]
please resolve this issue. thanks for the point. hopefully in the future these configurable items don't  need to be embedded in gogs binary.

**Comment by Unknwon** [comment]
> please resolve this issue.

What does this mean?

> hopefully in the future these configurable items don't need to be embedded in gogs binary.

See http://gogs.io/docs/advanced/configuration_cheat_sheet

**Comment by tjyang** [comment]
>please resolve this issue.
>What does this mean?
I mean you can mark this github issue as resolved/won't fix,  from project owner's perspective. Since this is a duplicate issue.

**Comment by Unknwon** [comment]
I see, thanks your confirmation.
