### ISSUE TITLE
Command line for install service in windows

### ISSUE THREAD

**Issue by tmx976** [gogits/docs#91]
Run the following command:

`C:\> sc create gogs start= auto binPath= ""C:\gogs\gogs.exe" web --config "C:\gogs\conf\app.ini""`

it's not good for me: I had to add backslash for escaping internal quote

`C:\> sc create gogs start= auto binPath= "\"C:\gogs\gogs.exe\" web --config \"C:\gogs\conf\app.ini\""`

**Comment by Unknwon** [comment]
Are you using standard command line prompt?

**Comment by tmx976** [comment]
Yes, I am.

**Comment by Unknwon** [comment]
Thanks.

Are you able to run Gogs as service after escaping internal quote?

```
C:\> sc create gogs start= auto binPath= "\"C:\gogs\gogs.exe\" web --config \"C:\gogs\conf\app.ini\""
```
