### ISSUE TITLE
Typo in master/de-DE/installation/install_from_source.md

### ISSUE THREAD

**Issue by AlexElvers** [gogits/docs#97]
The last line of the file is
`- Für detailliertere Instruktionen, darin enthalten Webserver und Datenbank aufsetzen, schaue dir die [detaillierten Schritte](/docs/advanced/configuration_for_soruce_builds) an`
but there is a typo in the link: It should be `configuration_for_source_builds`.

**Comment by Unknwon** [comment]
Thanks, please send a PR!
