### ISSUE TITLE
Better LDAP Documentation

### ISSUE THREAD

**Issue by barracks510** [gogits/docs#99]
It seems that a lot of users, including myself, are unable to find basic documentation on the LDAP features of Gogs. This makes it incredibly difficult to implement Gogs into academic environments. I would fully appreciate more documentation on the User auto creation feature, as it is not clear what is required for the functionality.

**Comment by Unknwon** [comment]
OK, will write a how-to for LDAP.

**Comment by tjyang** [comment]
I got ldap authentication to work in my office. I can  contribute on improving the doc on  LDAP also.

**Comment by Unknwon** [comment]
@tjyang https://github.com/gogits/docs/blob/master/en-US/features/authentication.md here you go.

**Comment by tjyang** [comment]
See https://github.com/tjyang/docs/blob/t/en-US/features/authentication.md for my WIP version.
Will submit PR with one commit when I am ready.

**Comment by Jitsusama** [comment]
It would be nice if there could be some description given on how the authentication mechanism works in general in Gogs. From what I can see perusing my admin interface, Gogs allows you to defined multiple authentication sources. How do they relate to each other? For instance; if I use LDAP-simple, do I create a local user entry in the database and then map it to the LDAP-simple authentication source? Does this mean I can mix PAM, LDAP and local database users on the system?

Some logical descriptions of how the various authentication options work together would make it much simpler for users to implement.

**Comment by Unknwon** [comment]
@Jitsusama quick answer to your question: you can mix them, but every username and e-mail address must be unique, you can't have some user appear in two different auth sources with same user name, or same e-mail address.
